// Bundled catalogs for quick-fill dropdowns in the Defaults panel.
//
// This is deliberately just plain data — no admin UI, no server. To add,
// edit, or retire an entry, edit this file, commit, and push; GitHub Pages
// picks it up on the next deploy. Selecting a preset only pre-fills fields;
// every field stays freely editable afterwards, so a slightly-wrong preset
// never blocks you.

// One entry per site — Company and Location are set together since every
// site in this org is its own Company *and* its own Location (matching the
// original import templates, where those two columns were always
// identical). If a site's Location ever needs to differ from its Company
// name, add a `location` field to that entry to override it.
//
// `shortCode` drives Asset Tag: every asset's Asset Tag is generated as
// `${shortCode}-${serial number}` (e.g. "SCL-MMLY7EE05514019418851M"),
// never typed by hand. Fill these in below as you get the real list — a
// site with no shortCode yet just leaves Asset Tag blank for you to fill
// in manually until then.
export const SITE_PRESETS = [
  { id: 'cardinal-newman', label: 'Cardinal Newman', shortCode: 'CNM' },
  { id: 'holy-family', label: 'Holy Family', shortCode: 'HFY' },
  { id: 'st-albans', label: 'St Albans', shortCode: 'SAB' },
  { id: 'st-annes', label: 'St Annes', shortCode: 'SAS' },
  { id: 'st-augustines', label: 'St Augustines', shortCode: 'SAU' },
  { id: 'st-charles-borromeo', label: 'St Charles Borromeo', shortCode: 'SCB' },
  { id: 'st-cuthbert-mayne', label: 'St Cuthbert Mayne', shortCode: 'SCM' },
  { id: 'st-cuthberts', label: 'St Cuthberts', shortCode: 'SCU' },
  { id: 'st-edmunds', label: 'St Edmunds', shortCode: 'SED' },
  { id: 'st-hugh-of-lincoln', label: 'St Hugh of Lincoln', shortCode: 'SHL' },
  { id: 'st-josephs-guildford', label: 'St Josephs (Guildford)', shortCode: 'SJG' },
  { id: 'st-polycarps', label: 'St Polycarps', shortCode: 'SPO' },
  { id: 'st-thomas-of-canterbury', label: 'St Thomas of Canterbury', shortCode: 'STC' },
  { id: 'the-marist', label: 'The Marist', shortCode: 'MAR' },
  { id: 'sjb', label: 'SJB', shortCode: 'SJB' },
  { id: 'salesian-school', label: 'Salesian School', shortCode: 'SAL' },
  { id: 'xavier-cet', label: 'Xavier CET', shortCode: 'XCET' },
  { id: 'sjb-safe', label: 'SJB - SAfE', shortCode: 'SAfE' },
  { id: 'sjb-mathshub', label: 'SJB - Mathshub', shortCode: 'SJB' },
  { id: 'st-francis', label: 'St Francis', shortCode: 'SFR' },
  { id: 'st-clements', label: 'St Clements', shortCode: 'SCL' },
  { id: 'st-josephs-redhill', label: 'St Josephs (Redhill)', shortCode: 'SJR' },
  { id: 'st-peters-leatherhead', label: 'St Peters (Leatherhead)', shortCode: 'SPL' },
  { id: 'st-josephs-dorking', label: 'St Josephs (Dorking)', shortCode: 'SJD' },
].map((s) => ({ ...s, company: s.label, location: s.location || s.label }));

// Keyed by asset type id (see js/templates.js). Each entry's `fields` only
// needs to set the keys that are meaningful for that model — anything not
// present in the asset type's columns is ignored, and anything you leave
// out (e.g. an unknown Cost) just leaves that field blank for you to fill
// in by hand. Field keys must match the `key` used in js/templates.js.
//
// `manufacturer` (optional) is metadata only — it's never written to a
// CSV. It drives the Manufacturer filter above the Model Preset dropdown
// and the default Warranty (Dell = 48 months, everything else = 12,
// per your stated policy) baked into `fields.warranty` below.
//
// monitor/touchscreen/laptop_pc/desktop_pc/tablet/wifi_access_point/
// hardware_other/network_switch/phone_telephony/printer_copier/server
// feed the fully working asset templates. Every other key here
// (docking_station) has no Freshservice import template wired up yet (see
// ASSET_TYPES in js/templates.js, where they're marked comingSoon) — their
// presets are captured here now so nothing from a product export gets
// lost, ready to use the moment a template exists for that type.
//
// This whole catalog was rebuilt from an actual Freshservice product
// export that includes each product's real Asset Type — every entry below
// is bucketed by that authoritative field, not guessed from the product
// name. Warranty defaults follow your stated rule; a handful of monitor/
// touchscreen/laptop/tablet models also carry Cost/Memory/Storage/OS
// values pulled from your own historical import data. Everything else
// only sets Product + Warranty — fill in the rest per row as you use it.
//
// Note: the export itself has a few internal inconsistencies (e.g. one
// "ProLiant DL380p Gen8" is typed Desktop while "ProLiant DL380 Gen10" is
// typed Server; "Pro Dock WD25" is Docking Station but "Pro Dock" is
// Hardware; "Telephone"/"KX-DT521" are Hardware, not Phone). Each entry
// here matches its product's Asset Type exactly as exported, even where
// that looks inconsistent — fix the source data in Freshservice if that's
// wrong, then regenerate.
export const MODEL_PRESETS = {
  monitor: [
    {
      id: "22m37a",
      label: "22M37A",
      manufacturer: "LG",
      fields: { product: "22M37A", warranty: 12 },
    },
    {
      id: "2310i",
      label: "2310i",
      manufacturer: "HP",
      fields: { product: "2310i", warranty: 12 },
    },
    {
      id: "ad80hw",
      label: "AD80HW",
      manufacturer: "Huawei",
      fields: { product: "AD80HW", warranty: 12 },
    },
    {
      id: "dell-pro-22",
      label: "Dell Pro 22",
      manufacturer: "Dell",
      fields: { product: "Dell Pro 22", warranty: 48 },
    },
    {
      id: "e1912hc",
      label: "E1912Hc",
      manufacturer: "Dell",
      fields: { product: "E1912Hc", warranty: 48 },
    },
    {
      id: "e1916he-monitor",
      label: "E1916HE Monitor",
      manufacturer: "Dell",
      fields: { product: "E1916HE Monitor", warranty: 48 },
    },
    {
      id: "e1916hef",
      label: "E1916Hef",
      manufacturer: "Dell",
      fields: { product: "E1916Hef", warranty: 48 },
    },
    {
      id: "e2214hb",
      label: "E2214Hb",
      manufacturer: "Dell",
      fields: { product: "E2214Hb", warranty: 48 },
    },
    {
      id: "e2216h",
      label: "E2216H",
      manufacturer: "Dell",
      fields: { product: "E2216H", warranty: 48 },
    },
    {
      id: "e2220h",
      label: "E2220H",
      manufacturer: "Dell",
      fields: { product: "E2220H", warranty: 48 },
    },
    {
      id: "e2221hn",
      label: "E2221HN",
      manufacturer: "Dell",
      fields: { product: "E2221HN", monitorSize: 22, warranty: 48 },
    },
    {
      id: "e2222h",
      label: "E2222H",
      manufacturer: "Dell",
      fields: { product: "E2222H", warranty: 48 },
    },
    {
      id: "e2283hs",
      label: "E2283HS",
      manufacturer: "Dell",
      fields: { product: "E2283HS", warranty: 48 },
    },
    {
      id: "e2425hm",
      label: "E2425HM",
      manufacturer: "Dell",
      fields: { product: "E2425HM", warranty: 48 },
    },
    {
      id: "h-360wds",
      label: "H-360WDS",
      fields: { product: "H-360WDS", warranty: 12 },
    },
    {
      id: "hp-compaq-le2002xi",
      label: "HP Compaq LE2002xi",
      manufacturer: "HP",
      fields: { product: "HP Compaq LE2002xi", warranty: 12 },
    },
    {
      id: "hp-s2031a",
      label: "HP S2031a",
      manufacturer: "HP",
      fields: { product: "HP S2031a", warranty: 12 },
    },
    {
      id: "lg-tv",
      label: "LG TV",
      manufacturer: "LG",
      fields: { product: "LG TV", warranty: 12 },
    },
    {
      id: "ls24d330hsx-en",
      label: "LS24D330HSX/EN",
      manufacturer: "Samsung",
      fields: { product: "LS24D330HSX/EN", warranty: 12 },
    },
    {
      id: "np-um361xg",
      label: "NP-UM361XG",
      manufacturer: "NEC",
      fields: { product: "NP-UM361XG", warranty: 12 },
    },
    {
      id: "p2179h",
      label: "P2179H",
      manufacturer: "Dell",
      fields: { product: "P2179H", warranty: 48 },
    },
    {
      id: "p2217",
      label: "P2217",
      manufacturer: "Dell",
      fields: { product: "P2217", warranty: 48 },
    },
    {
      id: "p2218",
      label: "P2218",
      manufacturer: "Dell",
      fields: { product: "P2218", warranty: 48 },
    },
    {
      id: "p223w",
      label: "P223W",
      manufacturer: "Dell",
      fields: { product: "P223W", warranty: 48 },
    },
    {
      id: "p2425h",
      label: "P2425H",
      manufacturer: "Dell",
      fields: { product: "P2425H", warranty: 48 },
    },
    {
      id: "p2722h",
      label: "P2722H",
      manufacturer: "Dell",
      fields: { product: "P2722H", warranty: 48 },
    },
    {
      id: "pro-22-monitor",
      label: "Pro 22 Monitor",
      manufacturer: "Dell",
      fields: { product: "Pro 22 Monitor", warranty: 48 },
    },
    {
      id: "pro-22-monitor-e2225hm",
      label: "Pro 22 Monitor E2225HM",
      manufacturer: "Dell",
      fields: { product: "Pro 22 Monitor E2225HM", warranty: 48 },
    },
    {
      id: "prodisplay-p201",
      label: "ProDisplay P201",
      manufacturer: "HP",
      fields: { product: "ProDisplay P201", warranty: 12 },
    },
    {
      id: "prodisplay-p202",
      label: "ProDisplay P202",
      manufacturer: "HP",
      fields: { product: "ProDisplay P202", warranty: 12 },
    },
    {
      id: "s2425hs",
      label: "S2425HS",
      manufacturer: "Dell",
      fields: { product: "S2425HS", warranty: 48 },
    },
    {
      id: "samsung",
      label: "Samsung",
      manufacturer: "Samsung",
      fields: { product: "Samsung", warranty: 12 },
    },
    {
      id: "se2216h",
      label: "SE2216H",
      manufacturer: "Dell",
      fields: { product: "SE2216H", warranty: 48 },
    },
    {
      id: "se2222h",
      label: "SE2222H",
      manufacturer: "Dell",
      fields: { product: "SE2222H", warranty: 48 },
    },
    {
      id: "se2417hgx",
      label: "SE2417HGX",
      manufacturer: "Dell",
      fields: { product: "SE2417HGX", warranty: 48 },
    },
    {
      id: "tft185w80ps",
      label: "TFT185W80PS",
      fields: { product: "TFT185W80PS", warranty: 12 },
    },
    {
      id: "v226hql",
      label: "V226HQL",
      fields: { product: "V226HQL", monitorSize: 22, warranty: 12, cost: 75 },
    },
  ],
  touchscreen: [
    {
      id: "55g-touch-slim-delx",
      label: "55G-Touch Slim-DELX",
      manufacturer: "G-Touch",
      fields: { product: "55G-Touch Slim-DELX", warranty: 12 },
    },
    {
      id: "75gt-4k-848",
      label: "75GT-4K-848",
      manufacturer: "G-Touch",
      fields: { product: "75GT-4K-848", warranty: 12 },
    },
    {
      id: "genee-g-touch",
      label: "Genee G-Touch",
      manufacturer: "Genee",
      fields: { product: "Genee G-Touch", warranty: 12 },
    },
    {
      id: "gx-v4-plus-series",
      label: "GX (V4) Plus Series",
      manufacturer: "SMART Technologies",
      fields: { product: "GX (V4) Plus Series", warranty: 12 },
    },
    {
      id: "mx265",
      label: "MX265",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265", warranty: 12 },
    },
    {
      id: "mx265-v2",
      label: "MX265-V2",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265-V2", warranty: 12 },
    },
    {
      id: "mx265-v2-c",
      label: "MX265-V2-C",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265-V2-C", warranty: 12 },
    },
    {
      id: "mx265-v3",
      label: "MX265-V3",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265-V3", warranty: 12 },
    },
    {
      id: "mx265-v4",
      label: "MX265-V4",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265-V4", warranty: 12 },
    },
    {
      id: "mx265-v5",
      label: "MX265-V5",
      manufacturer: "SMART Technologies",
      fields: { product: "MX265-V5", warranty: 12 },
    },
    {
      id: "mx275",
      label: "MX275",
      manufacturer: "SMART Technologies",
      fields: { product: "MX275", warranty: 12 },
    },
    {
      id: "mx275-v2",
      label: "MX275-V2",
      manufacturer: "SMART Technologies",
      fields: { product: "MX275-V2", warranty: 12 },
    },
    {
      id: "mx275-v3",
      label: "MX275-V3",
      manufacturer: "SMART Technologies",
      fields: { product: "MX275-V3", warranty: 12 },
    },
    {
      id: "mx275-v4",
      label: "MX275-V4",
      manufacturer: "SMART Technologies",
      fields: { product: "MX275-V4", warranty: 12 },
    },
    {
      id: "mx275-v5",
      label: "MX275-V5",
      manufacturer: "SMART Technologies",
      fields: { product: "MX275-V5", warranty: 12 },
    },
    {
      id: "prolite-te5564mis",
      label: "Prolite TE5564MIS",
      manufacturer: "iiyama",
      fields: { product: "Prolite TE5564MIS", warranty: 12, cost: 1500 },
    },
    {
      id: "rp650",
      label: "RP650+",
      manufacturer: "BenQ",
      fields: { product: "RP650+", warranty: 12 },
    },
    {
      id: "rp653k",
      label: "RP653K",
      manufacturer: "BenQ",
      fields: { product: "RP653K", warranty: 12 },
    },
    {
      id: "sbid-mx065-v2",
      label: "SBID-MX065-V2",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX065-V2", warranty: 12 },
    },
    {
      id: "sbid-mx065-v2-c",
      label: "SBID-MX065-V2-C",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX065-V2-C", warranty: 12 },
    },
    {
      id: "sbid-mx065-v4",
      label: "SBID-MX065-V4",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX065-V4", warranty: 12 },
    },
    {
      id: "sbid-mx075-v2",
      label: "SBID-MX075-V2",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX075-V2", warranty: 12 },
    },
    {
      id: "sbid-mx075-v2-c",
      label: "SBID-MX075-V2-C",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX075-V2-C", warranty: 12 },
    },
    {
      id: "sbid-mx075-v3",
      label: "SBID-MX075-V3",
      manufacturer: "SMART Technologies",
      fields: { product: "SBID-MX075-V3", warranty: 12 },
    },
    {
      id: "smart-board-gx-v4-plus-series",
      label: "SMART Board GX (V4) Plus Series",
      manufacturer: "SMART Technologies",
      fields: { product: "SMART Board GX (V4) Plus Series", warranty: 12 },
    },
    {
      id: "smartboard-6065",
      label: "SMARTBoard 6065",
      manufacturer: "SMART Technologies",
      fields: { product: "SMARTBoard 6065", warranty: 12 },
    },
    {
      id: "smartboard-6065-v2",
      label: "SMARTBoard 6065-V2",
      manufacturer: "SMART Technologies",
      fields: { product: "SMARTBoard 6065-V2", warranty: 12 },
    },
    {
      id: "t-series",
      label: "T-Series",
      fields: { product: "T-Series", warranty: 12 },
    },
  ],
  laptop_pc: [
    {
      id: "100e-chromebook-2nd-gen",
      label: "100e Chromebook 2nd Gen",
      manufacturer: "Lenovo",
      fields: { product: "100e Chromebook 2nd Gen", warranty: 12 },
    },
    {
      id: "14e-chromebook-gen-2",
      label: "14e Chromebook Gen 2",
      manufacturer: "Lenovo",
      fields: { product: "14e Chromebook Gen 2", warranty: 12 },
    },
    {
      id: "20bus01r08",
      label: "20BUS01R08",
      manufacturer: "Lenovo",
      fields: { product: "20BUS01R08", warranty: 12 },
    },
    {
      id: "20bus61r00",
      label: "20BUS61R00",
      manufacturer: "Lenovo",
      fields: { product: "20BUS61R00", warranty: 12 },
    },
    {
      id: "21ab000nuk",
      label: "21AB000NUK",
      manufacturer: "Lenovo",
      fields: { product: "21AB000NUK", warranty: 12 },
    },
    {
      id: "2356bq5",
      label: "2356BQ5",
      manufacturer: "Lenovo",
      fields: { product: "2356BQ5", warranty: 12 },
    },
    {
      id: "240-g7",
      label: "240 G7",
      manufacturer: "HP",
      fields: { product: "240 G7", warranty: 12 },
    },
    {
      id: "245-g8",
      label: "245 G8",
      manufacturer: "HP",
      fields: { product: "245 G8", warranty: 12 },
    },
    {
      id: "250-g10",
      label: "250 G10",
      manufacturer: "HP",
      fields: { product: "250 G10", warranty: 12 },
    },
    {
      id: "250-g5",
      label: "250 G5",
      manufacturer: "HP",
      fields: { product: "250 G5", warranty: 12 },
    },
    {
      id: "250-g6",
      label: "250 G6",
      manufacturer: "HP",
      fields: { product: "250 G6", warranty: 12 },
    },
    {
      id: "250-g7",
      label: "250 G7",
      manufacturer: "HP",
      fields: { product: "250 G7", warranty: 12 },
    },
    {
      id: "250-g8",
      label: "250 G8",
      manufacturer: "HP",
      fields: { product: "250 G8", warranty: 12 },
    },
    {
      id: "250-g9",
      label: "250 G9",
      manufacturer: "HP",
      fields: { product: "250 G9", warranty: 12 },
    },
    {
      id: "255-g5-notebook-pc",
      label: "255 G5 Notebook PC",
      manufacturer: "HP",
      fields: { product: "255 G5 Notebook PC", warranty: 12 },
    },
    {
      id: "255-g9",
      label: "255 G9",
      manufacturer: "HP",
      fields: { product: "255 G9", warranty: 12 },
    },
    {
      id: "80es",
      label: "80ES",
      manufacturer: "Lenovo",
      fields: { product: "80ES", warranty: 12 },
    },
    {
      id: "80j2",
      label: "80J2",
      manufacturer: "Lenovo",
      fields: { product: "80J2", warranty: 12 },
    },
    {
      id: "80lt",
      label: "80LT",
      manufacturer: "Lenovo",
      fields: { product: "80LT", warranty: 12 },
    },
    {
      id: "80th",
      label: "80TH",
      manufacturer: "Lenovo",
      fields: { product: "80TH", warranty: 12 },
    },
    {
      id: "80tl",
      label: "80TL",
      manufacturer: "Lenovo",
      fields: { product: "80TL", warranty: 12 },
    },
    {
      id: "80wq",
      label: "80WQ",
      manufacturer: "Lenovo",
      fields: { product: "80WQ", warranty: 12 },
    },
    {
      id: "81ax",
      label: "81AX",
      manufacturer: "Lenovo",
      fields: { product: "81AX", warranty: 12 },
    },
    {
      id: "81hq",
      label: "81HQ",
      manufacturer: "Lenovo",
      fields: { product: "81HQ", warranty: 12 },
    },
    {
      id: "82c5",
      label: "82C5",
      manufacturer: "Lenovo",
      fields: { product: "82C5", warranty: 12 },
    },
    {
      id: "82h8",
      label: "82H8",
      manufacturer: "Lenovo",
      fields: { product: "82H8", warranty: 12 },
    },
    {
      id: "82kd",
      label: "82KD",
      manufacturer: "Lenovo",
      fields: { product: "82KD", warranty: 12 },
    },
    {
      id: "82tt",
      label: "82TT",
      manufacturer: "Lenovo",
      fields: { product: "82TT", warranty: 12 },
    },
    {
      id: "chromebook-11-cb3-111-c730-c730e",
      label: "Chromebook 11 (CB3-111, C730, C730E)",
      manufacturer: "Acer",
      fields: { product: "Chromebook 11 (CB3-111, C730, C730E)", warranty: 12 },
    },
    {
      id: "chromebook-11a",
      label: "Chromebook 11a",
      manufacturer: "HP",
      fields: { product: "Chromebook 11a", warranty: 12 },
    },
    {
      id: "chromebook-11a-na0",
      label: "Chromebook 11a na0",
      manufacturer: "HP",
      fields: { product: "Chromebook 11a na0", warranty: 12 },
    },
    {
      id: "chromebook-14-g6",
      label: "Chromebook 14 G6",
      manufacturer: "HP",
      fields: { product: "Chromebook 14 G6", warranty: 12 },
    },
    {
      id: "chromebook-4",
      label: "Chromebook 4",
      manufacturer: "Samsung",
      fields: { product: "Chromebook 4", warranty: 12 },
    },
    {
      id: "chromebook-c204",
      label: "Chromebook C204",
      manufacturer: "ASUS",
      fields: { product: "Chromebook C204", warranty: 12 },
    },
    {
      id: "chromebox",
      label: "Chromebox",
      manufacturer: "Acer",
      fields: { product: "Chromebox", warranty: 12 },
    },
    {
      id: "dell-pro-14-pc14250",
      label: "Dell Pro 14 PC14250",
      manufacturer: "Dell",
      fields: { product: "Dell Pro 14 PC14250", warranty: 48 },
    },
    {
      id: "dynabook-satellite-pro-e10-s-10q",
      label: "Dynabook Satellite Pro E10-S-10Q",
      manufacturer: "Dynabook",
      fields: { product: "Dynabook Satellite Pro E10-S-10Q", warranty: 12 },
    },
    {
      id: "elitebook-840-g1",
      label: "EliteBook 840 G1",
      manufacturer: "HP",
      fields: { product: "EliteBook 840 G1", warranty: 12 },
    },
    {
      id: "elitebook-folio-9470m",
      label: "EliteBook Folio 9470m",
      manufacturer: "HP",
      fields: { product: "EliteBook Folio 9470m", warranty: 12 },
    },
    {
      id: "expertbook-p1403cva",
      label: "EXPERTBOOK P1403CVA",
      manufacturer: "ASUS",
      fields: { product: "EXPERTBOOK P1403CVA", warranty: 12 },
    },
    {
      id: "g15-5511",
      label: "G15 5511",
      manufacturer: "Dell",
      fields: { product: "G15 5511", warranty: 48 },
    },
    {
      id: "geobook-1e",
      label: "GEOBOOK 1E",
      manufacturer: "Geo",
      fields: { product: "GEOBOOK 1E", warranty: 12 },
    },
    {
      id: "hp-240",
      label: "HP 240",
      manufacturer: "HP",
      fields: { product: "HP 240", warranty: 12 },
    },
    {
      id: "hp-250",
      label: "HP 250",
      manufacturer: "HP",
      fields: { product: "HP 250", warranty: 12 },
    },
    {
      id: "hp-250-g9",
      label: "HP 250 G9",
      manufacturer: "HP",
      fields: { product: "HP 250 G9", warranty: 12 },
    },
    {
      id: "hp-255",
      label: "HP 255",
      manufacturer: "HP",
      fields: { product: "HP 255", warranty: 12 },
    },
    {
      id: "hp-255-g7",
      label: "HP 255 G7",
      manufacturer: "HP",
      fields: { product: "HP 255 G7", warranty: 12 },
    },
    {
      id: "hp-350-g2",
      label: "HP 350 G2",
      manufacturer: "HP",
      fields: { product: "HP 350 G2", warranty: 12 },
    },
    {
      id: "hp-k12-str11g5",
      label: "HP K12 STR11G5",
      manufacturer: "HP",
      fields: { product: "HP K12 STR11G5", warranty: 12 },
    },
    {
      id: "hp-stream-11-pro-g5",
      label: "HP Stream 11 Pro G5",
      manufacturer: "HP",
      fields: { product: "HP Stream 11 Pro G5", warranty: 12 },
    },
    {
      id: "inspiron-3505",
      label: "Inspiron 3505",
      manufacturer: "Dell",
      fields: { product: "Inspiron 3505", warranty: 48 },
    },
    {
      id: "k12-255g7",
      label: "K12 255G7",
      manufacturer: "HP",
      fields: { product: "K12 255G7", warranty: 12 },
    },
    {
      id: "k12-255g8",
      label: "K12 255G8",
      manufacturer: "HP",
      fields: { product: "K12 255G8", warranty: 12 },
    },
    {
      id: "latitude-3140",
      label: "Latitude 3140",
      manufacturer: "Dell",
      fields: { product: "Latitude 3140", warranty: 48 },
    },
    {
      id: "latitude-3190",
      label: "Latitude 3190",
      manufacturer: "Dell",
      fields: { product: "Latitude 3190", warranty: 48 },
    },
    {
      id: "latitude-3300",
      label: "Latitude 3300",
      manufacturer: "Dell",
      fields: { product: "Latitude 3300", warranty: 48 },
    },
    {
      id: "latitude-3310",
      label: "Latitude 3310",
      manufacturer: "Dell",
      fields: { product: "Latitude 3310", warranty: 48 },
    },
    {
      id: "latitude-3320",
      label: "Latitude 3320",
      manufacturer: "Dell",
      fields: { product: "Latitude 3320", warranty: 48 },
    },
    {
      id: "latitude-3380",
      label: "Latitude 3380",
      manufacturer: "Dell",
      fields: { product: "Latitude 3380", warranty: 48 },
    },
    {
      id: "latitude-3440",
      label: "Latitude 3440",
      manufacturer: "Dell",
      fields: { product: "Latitude 3440", warranty: 48 },
    },
    {
      id: "latitude-3450",
      label: "Latitude 3450",
      manufacturer: "Dell",
      fields: { product: "Latitude 3450", warranty: 48 },
    },
    {
      id: "latitude-3500",
      label: "Latitude 3500",
      manufacturer: "Dell",
      fields: { product: "Latitude 3500", warranty: 48 },
    },
    {
      id: "latitude-3510",
      label: "Latitude 3510",
      manufacturer: "Dell",
      fields: { product: "Latitude 3510", warranty: 48 },
    },
    {
      id: "latitude-3520",
      label: "Latitude 3520",
      manufacturer: "Dell",
      fields: { product: "Latitude 3520", warranty: 48 },
    },
    {
      id: "latitude-3540",
      label: "Latitude 3540",
      manufacturer: "Dell",
      fields: { product: "Latitude 3540", warranty: 48 },
    },
    {
      id: "latitude-3550",
      label: "Latitude 3550",
      manufacturer: "Dell",
      fields: { product: "Latitude 3550", warranty: 48 },
    },
    {
      id: "latitude-5340",
      label: "Latitude 5340",
      manufacturer: "Dell",
      fields: { product: "Latitude 5340", warranty: 48 },
    },
    {
      id: "latitude-5350",
      label: "Latitude 5350",
      manufacturer: "Dell",
      fields: { product: "Latitude 5350", warranty: 48 },
    },
    {
      id: "latitude-5430",
      label: "Latitude 5430",
      manufacturer: "Dell",
      fields: { product: "Latitude 5430", warranty: 48 },
    },
    {
      id: "latitude-5440",
      label: "Latitude 5440",
      manufacturer: "Dell",
      fields: { product: "Latitude 5440", warranty: 48 },
    },
    {
      id: "latitude-5550",
      label: "Latitude 5550",
      manufacturer: "Dell",
      fields: { product: "Latitude 5550", warranty: 48 },
    },
    {
      id: "latitude-e6420",
      label: "Latitude E6420",
      manufacturer: "Dell",
      fields: { product: "Latitude E6420", warranty: 48 },
    },
    {
      id: "lenovo-v15-82c7",
      label: "Lenovo V15-82C7",
      manufacturer: "Lenovo",
      fields: { product: "Lenovo V15-82C7", warranty: 12 },
    },
    {
      id: "macbook-air-13-inch-m4-2025",
      label: "MacBook Air (13-inch, M4, 2025)",
      manufacturer: "Apple",
      fields: { product: "MacBook Air (13-inch, M4, 2025)", warranty: 12 },
    },
    {
      id: "macbook-pro-13-inch-mid-2012",
      label: "MacBook Pro (13-inch Mid 2012)",
      manufacturer: "Apple",
      fields: { product: "MacBook Pro (13-inch Mid 2012)", warranty: 12 },
    },
    {
      id: "nblk-wax9x",
      label: "NBLK-WAX9X",
      manufacturer: "Honor",
      fields: { product: "NBLK-WAX9X", warranty: 12 },
    },
    {
      id: "opitplex-3000",
      label: "OpitPlex 3000",
      manufacturer: "Dell",
      fields: { product: "OpitPlex 3000", warranty: 48 },
    },
    {
      id: "optiplex-7010",
      label: "OptiPlex 7010",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 7010", warranty: 48 },
    },
    {
      id: "portege-x40-j",
      label: "PORTEGE X40-J",
      manufacturer: "Dynabook",
      fields: { product: "PORTEGE X40-J", warranty: 12 },
    },
    {
      id: "pro-14",
      label: "Pro 14",
      manufacturer: "Dell",
      fields: { product: "Pro 14", warranty: 48 },
    },
    {
      id: "pro-14-pc14250",
      label: "Pro 14 PC14250",
      manufacturer: "Dell",
      fields: { product: "Pro 14 PC14250", warranty: 48 },
    },
    {
      id: "pro-16",
      label: "Pro 16",
      manufacturer: "Dell",
      fields: { product: "Pro 16", warranty: 48 },
    },
    {
      id: "pro-16-pc16250",
      label: "Pro 16 PC16250",
      manufacturer: "Dell",
      fields: { product: "Pro 16 PC16250", warranty: 48 },
    },
    {
      id: "pro-17",
      label: "Pro 17",
      manufacturer: "Dell",
      fields: { product: "Pro 17", warranty: 48 },
    },
    {
      id: "probook-450-g10",
      label: "Probook 450 G10",
      manufacturer: "HP",
      fields: { product: "Probook 450 G10", warranty: 12 },
    },
    {
      id: "probook-450-g6",
      label: "Probook 450 G6",
      manufacturer: "HP",
      fields: { product: "Probook 450 G6", warranty: 12 },
    },
    {
      id: "probook-450-g7",
      label: "ProBook 450 G7",
      manufacturer: "HP",
      fields: { product: "ProBook 450 G7", warranty: 12 },
    },
    {
      id: "probook-450-g8-notebook-pc",
      label: "ProBook 450 G8 Notebook PC",
      manufacturer: "HP",
      fields: { product: "ProBook 450 G8 Notebook PC", warranty: 12 },
    },
    {
      id: "probook-450-g9",
      label: "Probook 450 G9",
      manufacturer: "HP",
      fields: { product: "Probook 450 G9", warranty: 12 },
    },
    {
      id: "probook-455-g10-notebook-pc",
      label: "ProBook 455 G10 Notebook PC",
      manufacturer: "HP",
      fields: { product: "ProBook 455 G10 Notebook PC", warranty: 12 },
    },
    {
      id: "probook-455-g9-notebook-pc",
      label: "ProBook 455 G9 Notebook PC",
      manufacturer: "HP",
      fields: { product: "ProBook 455 G9 Notebook PC", warranty: 12 },
    },
    {
      id: "probook-640-g5",
      label: "ProBook 640 G5",
      manufacturer: "HP",
      fields: { product: "ProBook 640 G5", warranty: 12 },
    },
    {
      id: "probook-x360",
      label: "Probook x360",
      manufacturer: "HP",
      fields: { product: "Probook x360", warranty: 12 },
    },
    {
      id: "satellite-pro",
      label: "Satellite Pro",
      manufacturer: "Toshiba",
      fields: { product: "Satellite Pro", warranty: 12 },
    },
    {
      id: "satellite-pro-c40-h-111",
      label: "SATELLITE PRO C40-H-111",
      manufacturer: "Toshiba",
      fields: { product: "SATELLITE PRO C40-H-111", processor: "Intel(R) Core(TM) i5-1035G1", memory: 8, disk: 240, warranty: 12, cost: 400 },
    },
    {
      id: "satellite-pro-e10-s",
      label: "SATELLITE PRO E10-S",
      manufacturer: "Dynabook",
      fields: { product: "SATELLITE PRO E10-S", warranty: 12 },
    },
    {
      id: "satellite-pro-r50-b",
      label: "Satellite Pro R50-B",
      manufacturer: "Toshiba",
      fields: { product: "Satellite Pro R50-B", warranty: 12 },
    },
    {
      id: "stream",
      label: "Stream",
      manufacturer: "HP",
      fields: { product: "Stream", warranty: 12 },
    },
    {
      id: "stream-11",
      label: "Stream 11",
      manufacturer: "HP",
      fields: { product: "Stream 11", warranty: 12 },
    },
    {
      id: "thinkpad-p14s-gen-2",
      label: "ThinkPad P14s Gen 2",
      manufacturer: "Lenovo",
      fields: { product: "ThinkPad P14s Gen 2", warranty: 12 },
    },
    {
      id: "tmp215-54",
      label: "TMP215-54",
      manufacturer: "Acer",
      fields: { product: "TMP215-54", warranty: 12 },
    },
    {
      id: "tmp255",
      label: "TMP255",
      manufacturer: "Acer",
      fields: { product: "TMP255", warranty: 12 },
    },
    {
      id: "travelmate-p214-52",
      label: "TravelMate P214-52",
      manufacturer: "Acer",
      fields: { product: "TravelMate P214-52", warranty: 12 },
    },
    {
      id: "travelmate-p215-54",
      label: "TravelMate P215-54",
      manufacturer: "Acer",
      fields: { product: "TravelMate P215-54", warranty: 12 },
    },
    {
      id: "travelmate-p253",
      label: "TravelMate P253",
      manufacturer: "Acer",
      fields: { product: "TravelMate P253", warranty: 12 },
    },
    {
      id: "travelmate-p257-m",
      label: "TravelMate P257-M",
      manufacturer: "Acer",
      fields: { product: "TravelMate P257-M", warranty: 12 },
    },
    {
      id: "v15-g2-alc",
      label: "V15 G2 ALC",
      manufacturer: "Lenovo",
      fields: { product: "V15 G2 ALC", warranty: 12 },
    },
    {
      id: "vivobook",
      label: "VivoBook",
      manufacturer: "ASUS",
      fields: { product: "VivoBook", warranty: 12 },
    },
    {
      id: "vivobook-x415ja",
      label: "VivoBook X415JA",
      manufacturer: "ASUS",
      fields: { product: "VivoBook X415JA", warranty: 12 },
    },
    {
      id: "vivobook-asuslaptop-x712ea-x712ea",
      label: "VivoBook_ASUSLaptop X712EA_X712EA",
      manufacturer: "ASUS",
      fields: { product: "VivoBook_ASUSLaptop X712EA_X712EA", warranty: 12 },
    },
    {
      id: "vostro-15",
      label: "Vostro 15",
      manufacturer: "Dell",
      fields: { product: "Vostro 15", warranty: 48 },
    },
    {
      id: "vostro-3401",
      label: "Vostro 3401",
      manufacturer: "Dell",
      fields: { product: "Vostro 3401", warranty: 48 },
    },
    {
      id: "vostro-3501",
      label: "Vostro 3501",
      manufacturer: "Dell",
      fields: { product: "Vostro 3501", warranty: 48 },
    },
    {
      id: "vostro-5481",
      label: "Vostro 5481",
      manufacturer: "Dell",
      fields: { product: "Vostro 5481", warranty: 48 },
    },
    {
      id: "zenbook-ux434da-um433da",
      label: "ZenBook UX434DA_UM433DA",
      manufacturer: "ASUS",
      fields: { product: "ZenBook UX434DA_UM433DA", warranty: 12 },
    },
  ],
  desktop_pc: [
    {
      id: "10nm0025uk",
      label: "10NM0025UK",
      manufacturer: "Lenovo",
      fields: { product: "10NM0025UK", warranty: 12 },
    },
    {
      id: "10ys000guk",
      label: "10YS000GUK",
      manufacturer: "Lenovo",
      fields: { product: "10YS000GUK", warranty: 12 },
    },
    {
      id: "11sws0av00",
      label: "11SWS0AV00",
      manufacturer: "Lenovo",
      fields: { product: "11SWS0AV00", warranty: 12 },
    },
    {
      id: "250-g4",
      label: "250 G4",
      manufacturer: "HP",
      fields: { product: "250 G4", warranty: 12 },
    },
    {
      id: "cms-9876",
      label: "CMS-9876",
      manufacturer: "CMS",
      fields: { product: "CMS-9876", warranty: 12 },
    },
    {
      id: "compaq-8000",
      label: "Compaq 8000",
      manufacturer: "HP",
      fields: { product: "Compaq 8000", warranty: 12 },
    },
    {
      id: "compaq-8200-elite-usdt-pc",
      label: "Compaq 8200 Elite USDT PC",
      manufacturer: "HP",
      fields: { product: "Compaq 8200 Elite USDT PC", warranty: 12 },
    },
    {
      id: "compaq-elite-8300",
      label: "Compaq Elite 8300",
      manufacturer: "HP",
      fields: { product: "Compaq Elite 8300", warranty: 12 },
    },
    {
      id: "eduminipc",
      label: "EduMiniPC",
      fields: { product: "EduMiniPC", warranty: 12 },
    },
    {
      id: "edupc",
      label: "EduPC",
      fields: { product: "EduPC", warranty: 12 },
    },
    {
      id: "elite-desktop",
      label: "Elite Desktop",
      manufacturer: "HP",
      fields: { product: "Elite Desktop", warranty: 12 },
    },
    {
      id: "eliteone-800-g6",
      label: "EliteOne 800 G6",
      manufacturer: "HP",
      fields: { product: "EliteOne 800 G6", warranty: 12 },
    },
    {
      id: "empc-i5-g10-8g240-edu",
      label: "EMPC-I5-G10-8G240-EDU",
      manufacturer: "Eduthing",
      fields: { product: "EMPC-I5-G10-8G240-EDU", warranty: 12 },
    },
    {
      id: "esprimo-d556-2",
      label: "Esprimo D556/2",
      manufacturer: "Fujitsu",
      fields: { product: "Esprimo D556/2", warranty: 12 },
    },
    {
      id: "esprimo-e420",
      label: "Esprimo E420",
      manufacturer: "Fujitsu",
      fields: { product: "Esprimo E420", warranty: 12 },
    },
    {
      id: "f0b100jxuk",
      label: "F0B100JXUK",
      manufacturer: "Lenovo",
      fields: { product: "F0B100JXUK", warranty: 12 },
    },
    {
      id: "gigabyte-technology-co-x570-gaming-x",
      label: "Gigabyte Technology Co X570 GAMING X",
      manufacturer: "Gigabyte",
      fields: { product: "Gigabyte Technology Co X570 GAMING X", warranty: 12 },
    },
    {
      id: "h81m-ds2v",
      label: "H81M-DS2V",
      manufacturer: "Novatech",
      fields: { product: "H81M-DS2V", warranty: 12 },
    },
    {
      id: "hp-240-g7",
      label: "HP 240 G7",
      manufacturer: "HP",
      fields: { product: "HP 240 G7", warranty: 12 },
    },
    {
      id: "hp-290-g1",
      label: "HP 290 G1",
      manufacturer: "HP",
      fields: { product: "HP 290 G1", warranty: 12 },
    },
    {
      id: "hp-290-g2",
      label: "HP 290 G2",
      manufacturer: "HP",
      fields: { product: "HP 290 G2", warranty: 12 },
    },
    {
      id: "k12-pro-sff-400-g9",
      label: "K12 Pro SFF 400 G9",
      manufacturer: "HP",
      fields: { product: "K12 Pro SFF 400 G9", warranty: 12 },
    },
    {
      id: "lenovo-m91p-4518ry2",
      label: "Lenovo M91p - 4518RY2",
      manufacturer: "Lenovo",
      fields: { product: "Lenovo M91p - 4518RY2", warranty: 12 },
    },
    {
      id: "lenovo-thinkcentre-e73-10aw008puk",
      label: "Lenovo ThinkCentre E73 - 10AW008PUK",
      manufacturer: "Lenovo",
      fields: { product: "Lenovo ThinkCentre E73 - 10AW008PUK", warranty: 12 },
    },
    {
      id: "mac-mini-m2",
      label: "Mac Mini M2",
      manufacturer: "Apple",
      fields: { product: "Mac Mini M2", warranty: 12 },
    },
    {
      id: "mac-mini-m4",
      label: "Mac Mini M4",
      manufacturer: "Apple",
      fields: { product: "Mac Mini M4", warranty: 12 },
    },
    {
      id: "n-a",
      label: "N/A",
      fields: { product: "N/A", warranty: 12 },
    },
    {
      id: "ns-optimum",
      label: "NS Optimum",
      fields: { product: "NS Optimum", warranty: 12 },
    },
    {
      id: "optiplex-3000",
      label: "OptiPlex 3000",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3000", warranty: 48 },
    },
    {
      id: "optiplex-3020",
      label: "OptiPlex 3020",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3020", warranty: 48 },
    },
    {
      id: "optiplex-3040",
      label: "OptiPlex 3040",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3040", warranty: 48 },
    },
    {
      id: "optiplex-3050",
      label: "OptiPlex 3050",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3050", warranty: 48 },
    },
    {
      id: "optiplex-3060",
      label: "OptiPlex 3060",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3060", warranty: 48 },
    },
    {
      id: "optiplex-3070",
      label: "OptiPlex 3070",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3070", warranty: 48 },
    },
    {
      id: "optiplex-3080",
      label: "OptiPlex 3080",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3080", warranty: 48 },
    },
    {
      id: "optiplex-3090",
      label: "OptiPlex 3090",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3090", warranty: 48 },
    },
    {
      id: "optiplex-3280-aio",
      label: "OptiPlex 3280 AIO",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 3280 AIO", warranty: 48 },
    },
    {
      id: "optiplex-5000",
      label: "OptiPlex 5000",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 5000", warranty: 48 },
    },
    {
      id: "optiplex-5070",
      label: "OptiPlex 5070",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 5070", warranty: 48 },
    },
    {
      id: "optiplex-5270-aio",
      label: "OptiPlex 5270 AIO",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 5270 AIO", warranty: 48 },
    },
    {
      id: "optiplex-7000-sff",
      label: "Optiplex 7000 SFF",
      manufacturer: "Dell",
      fields: { product: "Optiplex 7000 SFF", warranty: 48 },
    },
    {
      id: "optiplex-7020",
      label: "OptiPlex 7020",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 7020", warranty: 48 },
    },
    {
      id: "optiplex-7440-aio",
      label: "OptiPlex 7440 AIO",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 7440 AIO", warranty: 48 },
    },
    {
      id: "optiplex-9010-aio",
      label: "OptiPlex 9010 AIO",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 9010 AIO", warranty: 48 },
    },
    {
      id: "optiplex-9020",
      label: "OptiPlex 9020",
      manufacturer: "Dell",
      fields: { product: "OptiPlex 9020", warranty: 48 },
    },
    {
      id: "optiplex-sff-7010",
      label: "OptiPlex SFF 7010",
      manufacturer: "Dell",
      fields: { product: "OptiPlex SFF 7010", warranty: 48 },
    },
    {
      id: "optiplex-sff-7021",
      label: "Optiplex SFF 7021",
      manufacturer: "Dell",
      fields: { product: "Optiplex SFF 7021", warranty: 48 },
    },
    {
      id: "optiplex-sff-7022",
      label: "Optiplex SFF 7022",
      manufacturer: "Dell",
      fields: { product: "Optiplex SFF 7022", warranty: 48 },
    },
    {
      id: "pc-cx00368",
      label: "PC-CX00368",
      manufacturer: "Novatech",
      fields: { product: "PC-CX00368", warranty: 12 },
    },
    {
      id: "pc-cx00449",
      label: "PC-CX00449",
      manufacturer: "Novatech",
      fields: { product: "PC-CX00449", warranty: 12 },
    },
    {
      id: "pc-cx00774",
      label: "PC-CX00774",
      manufacturer: "Novatech",
      fields: { product: "PC-CX00774", warranty: 12 },
    },
    {
      id: "pro-sff-290-g9-desktop-pc",
      label: "Pro SFF 290 G9 Desktop PC",
      manufacturer: "HP",
      fields: { product: "Pro SFF 290 G9 Desktop PC", warranty: 12 },
    },
    {
      id: "pro-slim-qcs1250",
      label: "Pro Slim QCS1250",
      manufacturer: "Dell",
      fields: { product: "Pro Slim QCS1250", memory: 16, disk: 512, warranty: 48 },
    },
    {
      id: "prodesk-400-g1-sff",
      label: "ProDesk 400 G1 SFF",
      manufacturer: "HP",
      fields: { product: "ProDesk 400 G1 SFF", warranty: 12 },
    },
    {
      id: "prodesk-400-g3-sff",
      label: "ProDesk 400 G3 SFF",
      manufacturer: "HP",
      fields: { product: "ProDesk 400 G3 SFF", warranty: 12 },
    },
    {
      id: "proliant-dl380p-gen8",
      label: "ProLiant DL380p Gen8",
      manufacturer: "HP",
      fields: { product: "ProLiant DL380p Gen8", warranty: 12 },
    },
    {
      id: "proone-400-g3",
      label: "ProOne 400 G3",
      manufacturer: "HP",
      fields: { product: "ProOne 400 G3", warranty: 12 },
    },
    {
      id: "proone-440-g5",
      label: "ProOne 440 G5",
      manufacturer: "HP",
      fields: { product: "ProOne 440 G5", warranty: 12 },
    },
    {
      id: "proone-440-g6",
      label: "ProOne 440 G6",
      manufacturer: "HP",
      fields: { product: "ProOne 440 G6", warranty: 12 },
    },
    {
      id: "proone-440-g9",
      label: "ProOne 440 G9",
      manufacturer: "HP",
      fields: { product: "ProOne 440 G9", warranty: 12 },
    },
    {
      id: "sff-pc",
      label: "SFF PC",
      manufacturer: "NS Optimum",
      fields: { product: "SFF PC", warranty: 12 },
    },
    {
      id: "tmp255-m",
      label: "TMP255-M",
      manufacturer: "Acer",
      fields: { product: "TMP255-M", warranty: 12 },
    },
    {
      id: "unbranded",
      label: "Unbranded",
      fields: { product: "Unbranded", warranty: 12 },
    },
    {
      id: "veriton-l4620g",
      label: "Veriton L4620G",
      manufacturer: "Acer",
      fields: { product: "Veriton L4620G", warranty: 12 },
    },
    {
      id: "veriton-l670g",
      label: "Veriton L670G",
      manufacturer: "Acer",
      fields: { product: "Veriton L670G", warranty: 12 },
    },
    {
      id: "veriton-n4690gt",
      label: "Veriton N4690GT",
      manufacturer: "Acer",
      fields: { product: "Veriton N4690GT", warranty: 12 },
    },
    {
      id: "veriton-n4710gt",
      label: "Veriton N4710GT",
      manufacturer: "Acer",
      fields: { product: "Veriton N4710GT", warranty: 12 },
    },
    {
      id: "veriton-vero-n4720gt",
      label: "Veriton Vero N4720GT",
      manufacturer: "Acer",
      fields: { product: "Veriton Vero N4720GT", warranty: 12 },
    },
    {
      id: "veriton-x2610g",
      label: "Veriton X2610G",
      manufacturer: "Acer",
      fields: { product: "Veriton X2610G", warranty: 12 },
    },
    {
      id: "veriton-x2611g",
      label: "Veriton X2611G",
      manufacturer: "Acer",
      fields: { product: "Veriton X2611G", warranty: 12 },
    },
    {
      id: "veriton-x275",
      label: "Veriton X275",
      manufacturer: "Acer",
      fields: { product: "Veriton X275", warranty: 12 },
    },
    {
      id: "zoostorm-pc",
      label: "Zoostorm PC",
      manufacturer: "Zoostorm",
      fields: { product: "Zoostorm PC", warranty: 12 },
    },
    {
      id: "zoostorm-sff",
      label: "ZooStorm SFF",
      manufacturer: "Zoostorm",
      fields: { product: "ZooStorm SFF", warranty: 12 },
    },
    {
      id: "zoosuite",
      label: "Zoosuite",
      fields: { product: "Zoosuite", warranty: 12 },
    },
  ],
  tablet: [
    {
      id: "fire-hd-10-7th-gen",
      label: "Fire HD 10 (7th Gen.)",
      manufacturer: "Amazon",
      fields: { product: "Fire HD 10 (7th Gen.)", os: "Fire OS", warranty: 12 },
    },
    {
      id: "ipad-10th-gen",
      label: "iPad 10th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 10th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-4th-gen",
      label: "iPad 4th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 4th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-5th-gen",
      label: "iPad 5th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 5th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-6th-gen",
      label: "iPad 6th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 6th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-7th-gen",
      label: "iPad 7th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 7th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-8th-gen",
      label: "iPad 8th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 8th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-9th-gen",
      label: "iPad 9th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad 9th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-a16",
      label: "iPad A16",
      manufacturer: "Apple",
      fields: { product: "iPad A16", os: "iPadOS", storage: 128, warranty: 12, cost: 350 },
    },
    {
      id: "ipad-air",
      label: "iPad Air",
      manufacturer: "Apple",
      fields: { product: "iPad Air", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-air-m2",
      label: "iPad Air (M2)",
      manufacturer: "Apple",
      fields: { product: "iPad Air (M2)", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-air-2",
      label: "iPad Air 2",
      manufacturer: "Apple",
      fields: { product: "iPad Air 2", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-air-4th-gen",
      label: "iPad Air 4th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad Air 4th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-air-5th-gen",
      label: "iPad Air 5th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad Air 5th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-mini",
      label: "iPad Mini",
      manufacturer: "Apple",
      fields: { product: "iPad Mini", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-mini-2",
      label: "iPad Mini 2",
      manufacturer: "Apple",
      fields: { product: "iPad Mini 2", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-mini-3",
      label: "iPad Mini 3",
      manufacturer: "Apple",
      fields: { product: "iPad Mini 3", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-mini-4",
      label: "iPad Mini 4",
      manufacturer: "Apple",
      fields: { product: "iPad Mini 4", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-pro-12-9-4th-gen",
      label: "iPad Pro 12.9 4th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad Pro 12.9 4th Gen", os: "iPadOS", warranty: 12 },
    },
    {
      id: "ipad-pro-12-9-5th-gen",
      label: "iPad Pro 12.9 5th Gen",
      manufacturer: "Apple",
      fields: { product: "iPad Pro 12.9 5th Gen", os: "iPadOS", warranty: 12 },
    },
  ],
  printer_copier: [
    {
      id: "dna",
      label: "DNA",
      manufacturer: "Javelin",
      fields: { product: "DNA", warranty: 12 },
    },
    {
      id: "e-studio2010ac",
      label: "e-STUDIO2010AC",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO2010AC", warranty: 12 },
    },
    {
      id: "e-studio3525ac",
      label: "e-STUDIO3525AC",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO3525AC", warranty: 12 },
    },
    {
      id: "e-studio409cs-7531430034ml6-cxtgv-230-045",
      label: "e-STUDIO409CS 7531430034ML6 CXTGV.230.045",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO409CS 7531430034ML6 CXTGV.230.045", warranty: 12 },
    },
    {
      id: "e-studio409p-46014524104w5-mslbd-230-047",
      label: "e-STUDIO409P 46014524104W5 MSLBD.230.047",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO409P 46014524104W5 MSLBD.230.047", warranty: 12 },
    },
    {
      id: "e-studio4525ac",
      label: "e-STUDIO4525AC",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO4525AC", warranty: 12 },
    },
    {
      id: "e-studio6528a",
      label: "e-STUDIO6528A",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO6528A", warranty: 12 },
    },
    {
      id: "e-studio7527ac",
      label: "e-STUDIO7527AC",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO7527AC", warranty: 12 },
    },
    {
      id: "e-studio9029a",
      label: "e-STUDIO9029A",
      manufacturer: "Toshiba",
      fields: { product: "e-STUDIO9029A", warranty: 12 },
    },
    {
      id: "ecosys-m5526cdn",
      label: "ECOSYS M5526cdn",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS M5526cdn", warranty: 12 },
    },
    {
      id: "ecosys-p2040dn",
      label: "ECOSYS P2040dn",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS P2040dn", warranty: 12 },
    },
    {
      id: "ecosys-p5026cdn",
      label: "ECOSYS P5026cdn",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS P5026cdn", warranty: 12 },
    },
    {
      id: "ecosys-p5026cdw",
      label: "ECOSYS P5026cdw",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS P5026cdw", warranty: 12 },
    },
    {
      id: "ecosys-p6026cdn",
      label: "ECOSYS P6026cdn",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS P6026cdn", warranty: 12 },
    },
    {
      id: "ecosys-p6230cdn",
      label: "ECOSYS P6230cdn",
      manufacturer: "Kyocera",
      fields: { product: "ECOSYS P6230cdn", warranty: 12 },
    },
    {
      id: "fs-2020d",
      label: "FS-2020D",
      manufacturer: "Kyocera",
      fields: { product: "FS-2020D", warranty: 12 },
    },
    {
      id: "fs-2100dn",
      label: "FS-2100DN",
      manufacturer: "Kyocera",
      fields: { product: "FS-2100DN", warranty: 12 },
    },
    {
      id: "generic-text-only",
      label: "Generic / Text Only",
      fields: { product: "Generic / Text Only", warranty: 12 },
    },
    {
      id: "jack",
      label: "JACK",
      manufacturer: "Javelin",
      fields: { product: "JACK", warranty: 12 },
    },
    {
      id: "labelwriter-450",
      label: "LabelWriter 450",
      manufacturer: "Dymo",
      fields: { product: "LabelWriter 450", warranty: 12 },
    },
    {
      id: "laserjet-1320-series",
      label: "LaserJet 1320 series",
      manufacturer: "HP",
      fields: { product: "LaserJet 1320 series", warranty: 12 },
    },
    {
      id: "laserjet-p2055dn",
      label: "LaserJet P2055dn",
      manufacturer: "HP",
      fields: { product: "LaserJet P2055dn", warranty: 12 },
    },
    {
      id: "mp-c3503",
      label: "MP C3503",
      manufacturer: "Ricoh",
      fields: { product: "MP C3503", warranty: 12 },
    },
    {
      id: "xerox-b205",
      label: "Xerox B205",
      manufacturer: "Xerox",
      fields: { product: "Xerox B205", warranty: 12 },
    },
    {
      id: "xerox-b225",
      label: "Xerox B225",
      manufacturer: "Xerox",
      fields: { product: "Xerox B225", warranty: 12 },
    },
  ],
  phone_telephony: [
    {
      id: "splicecom-pcs-542",
      label: "Splicecom PCS 542",
      manufacturer: "Splicecom",
      fields: { product: "Splicecom PCS 542", warranty: 12 },
    },
  ],
  wifi_access_point: [
    {
      id: "r350",
      label: "R350",
      manufacturer: "Ruckus",
      fields: { product: "R350", warranty: 12 },
    },
    {
      id: "r510",
      label: "R510",
      manufacturer: "Ruckus",
      fields: { product: "R510", warranty: 12 },
    },
    {
      id: "r550",
      label: "R550",
      manufacturer: "Ruckus",
      fields: { product: "R550", warranty: 12 },
    },
    {
      id: "r560",
      label: "R560",
      manufacturer: "Ruckus",
      fields: { product: "R560", warranty: 12 },
    },
    {
      id: "r610",
      label: "R610",
      manufacturer: "Ruckus",
      fields: { product: "R610", warranty: 12 },
    },
    {
      id: "r650",
      label: "R650",
      manufacturer: "Ruckus",
      fields: { product: "R650", warranty: 12 },
    },
    {
      id: "r750",
      label: "R750",
      manufacturer: "Ruckus",
      fields: { product: "R750", warranty: 12 },
    },
    {
      id: "r760",
      label: "R760",
      manufacturer: "Ruckus",
      fields: { product: "R760", warranty: 12 },
    },
    {
      id: "xv2-2",
      label: "XV2-2",
      manufacturer: "Cambium Networks",
      fields: { product: "XV2-2", warranty: 12 },
    },
  ],
  network_switch: [
    {
      id: "2530-48g",
      label: "2530-48G",
      manufacturer: "Aruba",
      fields: { product: "2530-48G", warranty: 12 },
    },
  ],
  server: [
    {
      id: "proliant-dl380-gen10",
      label: "ProLiant DL380 Gen10",
      manufacturer: "HP",
      fields: { product: "ProLiant DL380 Gen10", warranty: 12 },
    },
    {
      id: "proliant-ml350-gen10",
      label: "ProLiant ML350 Gen10",
      manufacturer: "HP",
      fields: { product: "ProLiant ML350 Gen10", warranty: 12 },
    },
    {
      id: "virtual-machine",
      label: "Virtual Machine",
      fields: { product: "Virtual Machine", warranty: 12 },
    },
  ],
  docking_station: [
    {
      id: "pro-dock-wd25",
      label: "Pro Dock WD25",
      manufacturer: "Dell",
      fields: { product: "Pro Dock WD25", warranty: 48 },
    },
  ],
  hardware_other: [
    {
      id: "av1",
      label: "AV1",
      manufacturer: "No Isolation",
      fields: { product: "AV1", warranty: 12 },
    },
    {
      id: "kx-dt521",
      label: "KX-DT521",
      manufacturer: "Panasonic",
      fields: { product: "KX-DT521", warranty: 12 },
    },
    {
      id: "monitor",
      label: "Monitor",
      fields: { product: "Monitor", warranty: 12 },
    },
    {
      id: "power-amplifier",
      label: "Power Amplifier",
      fields: { product: "Power Amplifier", warranty: 12 },
    },
    {
      id: "pro-dock",
      label: "Pro Dock",
      manufacturer: "Dell",
      fields: { product: "Pro Dock", warranty: 48 },
    },
    {
      id: "projector",
      label: "Projector",
      fields: { product: "Projector", warranty: 12 },
    },
    {
      id: "studio305cs",
      label: "Studio305CS",
      fields: { product: "Studio305CS", warranty: 12 },
    },
    {
      id: "studio338cs",
      label: "Studio338CS",
      fields: { product: "Studio338CS", warranty: 12 },
    },
    {
      id: "studio7516ac",
      label: "Studio7516AC",
      manufacturer: "Toshiba",
      fields: { product: "Studio7516AC", warranty: 12 },
    },
    {
      id: "telephone",
      label: "Telephone",
      fields: { product: "Telephone", warranty: 12 },
    },
    {
      id: "tou200030",
      label: "TOU200030",
      fields: { product: "TOU200030", warranty: 12 },
    },
    {
      id: "vpl-ex175",
      label: "VPL-EX175",
      manufacturer: "Sony",
      fields: { product: "VPL-EX175", warranty: 12 },
    },
  ],
};
